name: Compile Release Candidate

on:
  workflow_dispatch:

jobs:
  build-release-candidate:
    if: startsWith(github.ref_name, 'release/')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - pio_env: gh_release_rc
            artifact: firmware.bin
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          enable-cache: false

      - name: Install PlatformIO Core
        run: uv pip install --system -U https://github.com/pioarduino/platformio-core/archive/refs/tags/v6.1.19.zip

      - name: Extract env
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "BRANCH_SUFFIX=${GITHUB_REF_NAME#release/}" >> $GITHUB_ENV

      - name: Build CrossPoint Release Candidate
        env:
          CROSSPOINT_RC_HASH: ${{ env.SHORT_SHA }}
        run: pio run -e "${{ matrix.pio_env }}"

      - name: Name release candidate asset
        if: matrix.artifact != 'firmware.bin'
        run: cp ".pio/build/${{ matrix.pio_env }}/firmware.bin" ".pio/build/${{ matrix.pio_env }}/${{ matrix.artifact }}"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CPR-vCodex-RC-${{ env.BRANCH_SUFFIX }}-${{ matrix.pio_env }}
          path: |
            .pio/build/${{ matrix.pio_env }}/bootloader.bin
            .pio/build/${{ matrix.pio_env }}/${{ matrix.artifact }}
            .pio/build/${{ matrix.pio_env }}/firmware.elf
            .pio/build/${{ matrix.pio_env }}/firmware.map
            .pio/build/${{ matrix.pio_env }}/partitions.bin
